# Generated by Django 2.0.dev20170822152607 on 2017-08-25 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaarwaan', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marks',
            new_name='Mark',
        ),
    ]
